### ISSUE TITLE
npm install fails: posix@1.0.0 can not be built

### ISSUE THREAD

**Issue by nikos** [jmakeig/marklogic-syslog-viewer#15]
On a fairly up-to-date Mac (using homebrew), when trying to "npm install" right after cloning this project I get the following error message:

```
npm install
npm WARN package.json log-viewer@0.1.0 No repository field.
npm WARN package.json log-viewer@0.1.0 license should be a valid SPDX license expression
npm WARN engine marklogic@1.0.3: wanted: {"node":">=0.10.26 <0.11"} (current: {"node":"0.12.4","npm":"2.10.1"})

> posix@1.0.0 install /Users/niko/src/marklogic/jmakeig/marklogic-syslog-viewer/node_modules/winston-posix-syslog/node_modules/posix
> node-gyp rebuild

  CXX(target) Release/obj.target/posix/src/posix.o
../src/posix.cc:16:41: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> node_getppid(const Arguments& args) {
                                        ^~~~~~~~~
                                        v8::internal::Arguments
/Users/niko/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/posix.cc:17:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/niko/.node-gyp/0.12.4/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/posix.cc:19:12: error: member access into incomplete type 'const v8::internal::Arguments'
    if(args.Length() != 0) {
           ^
/Users/niko/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/posix.cc:20:16: error: no member named 'New' in 'v8::String'
        return EXCEPTION("getppid: takes no arguments");
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/posix.cc:11:64: note: expanded from macro 'EXCEPTION'
#define EXCEPTION(msg) ThrowException(Exception::Error(String::New(msg)))
                                                       ~~~~~~~~^
../src/posix.cc:23:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(Integer::New(getppid()));
           ~~~~~ ^
../src/posix.cc:23:46: error: too few arguments to function call, expected 2, have 1
    return scope.Close(Integer::New(getppid()));
                       ~~~~~~~~~~~~          ^
/Users/niko/.node-gyp/0.12.4/deps/v8/include/v8.h:2012:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../src/posix.cc:26:41: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> node_getpgid(const Arguments& args) {
                                        ^~~~~~~~~
                                        v8::internal::Arguments
/Users/niko/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/posix.cc:27:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/niko/.node-gyp/0.12.4/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/posix.cc:29:12: error: member access into incomplete type 'const v8::internal::Arguments'
    if(args.Length() != 1) {
           ^
/Users/niko/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/posix.cc:30:16: error: no member named 'New' in 'v8::String'
        return EXCEPTION("getpgid: takes exactly one argument");
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/posix.cc:11:64: note: expanded from macro 'EXCEPTION'
#define EXCEPTION(msg) ThrowException(Exception::Error(String::New(msg)))
                                                       ~~~~~~~~^
../src/posix.cc:33:14: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    if (!args[0]->IsNumber()) {
         ~~~~^~
../src/posix.cc:34:16: error: no member named 'New' in 'v8::String'
        return EXCEPTION("getpgid: first argument must be a integer");
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/posix.cc:11:64: note: expanded from macro 'EXCEPTION'
#define EXCEPTION(msg) ThrowException(Exception::Error(String::New(msg)))
                                                       ~~~~~~~~^
../src/posix.cc:37:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(Integer::New(getpgid(args[0]->IntegerValue())));
           ~~~~~ ^
../src/posix.cc:37:49: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    return scope.Close(Integer::New(getpgid(args[0]->IntegerValue())));
                                            ~~~~^~
../src/posix.cc:40:41: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> node_geteuid(const Arguments& args) {
                                        ^~~~~~~~~
                                        v8::internal::Arguments
/Users/niko/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/posix.cc:41:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/niko/.node-gyp/0.12.4/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/posix.cc:43:12: error: member access into incomplete type 'const v8::internal::Arguments'
    if(args.Length() != 0) {
           ^
/Users/niko/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/posix.cc:44:16: error: no member named 'New' in 'v8::String'
        return EXCEPTION("geteuid: takes no arguments");
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/posix.cc:11:64: note: expanded from macro 'EXCEPTION'
#define EXCEPTION(msg) ThrowException(Exception::Error(String::New(msg)))
                                                       ~~~~~~~~^
../src/posix.cc:47:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(Integer::New(geteuid()));
           ~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/posix/src/posix.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/niko/src/marklogic/jmakeig/marklogic-syslog-viewer/node_modules/winston-posix-syslog/node_modules/posix
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! posix@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the posix@1.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the posix package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls posix
npm ERR! There is likely additional logging output above.
```

**Comment by jmakeig** [comment]
I haven't tried this with 0.12. I'm still running 0.10.31. It looks like there have been some native API changes.
